### ISSUE TITLE
enhancement acces to value in Form::config

### ISSUE THREAD

**Issue by agborkowski** [UnionOfRAD/lithium#906]
i want to override text template or add new template for inputs like this

```php
$this->form->config(['templates' => [
    'text' => '<span id="{:name}">{:value}</span>', #for view mode ;)
    'span' => '<span id="{:name}">{:value}</span>'
  ]]);
```

but i dont have acces to :value any solutions ?

**Comment by davidpersson** [comment]
I'm closing this ticket as the following code does the trick without us needing to add additional code to the core:

```php
$this->form->field('name', [
     'readonly' => !$isEditMode
]);
```

```css
/* render input as it would not be one */
input[readonly] {
  border: none;
  background: white;
  padding: 0;
}
```

Alternatively subclass the form helper as @jails suggested.
